2018-10-30 10:44:54.718 [error] <0.530.0>CRASH REPORT Process <0.530.0> with 0 neighbours exited with reason: {aborted,{no_exists,[tab_role]}} in mnesia:abort/1 line 351
2018-10-30 10:44:54.718 [error] <0.521.0>Supervisor cellphone_sup had child role_sup started with role_sup:start_link() at undefined exit with reason {aborted,{no_exists,[tab_role]}} in context start_error
2018-10-30 10:44:54.719 [error] <0.519.0>CRASH REPORT Process <0.519.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,role_sup,{aborted,{no_exists,[tab_role]}}}},{cellphone_app,start,[normal,[]]}} in application_master:init/4 line 138
2018-10-30 10:45:19.508 [error] <0.530.0>CRASH REPORT Process <0.530.0> with 0 neighbours exited with reason: {aborted,{no_exists,[tab_role]}} in mnesia:abort/1 line 351
2018-10-30 10:45:19.508 [error] <0.521.0>Supervisor cellphone_sup had child role_sup started with role_sup:start_link() at undefined exit with reason {aborted,{no_exists,[tab_role]}} in context start_error
2018-10-30 10:45:19.509 [error] <0.519.0>CRASH REPORT Process <0.519.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,role_sup,{aborted,{no_exists,[tab_role]}}}},{cellphone_app,start,[normal,[]]}} in application_master:init/4 line 138
2018-10-30 11:01:15.205 [error] <0.540.0>CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: call to undefined function mneisa:system_info(extra_db_nodes)
2018-10-30 11:01:15.205 [error] <0.539.0>Supervisor data_sup had child data_server started with data_server:start_link() at undefined exit with reason call to undefined function mneisa:system_info(extra_db_nodes) in context start_error
2018-10-30 11:01:15.208 [error] <0.538.0>Supervisor cellphone_sup had child data_sup started with data_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,data_server,{undef,[{mneisa,system_info,[extra_db_nodes],[]},{data_server,do_init,0,[{file,"/data/cellphone/_build/default/lib/cellphone/src/data/data_server.erl"},{line,63}]},{data_server,init,1,[{file,"/data/cellphone/_build/default/lib/cellphone/src/data/data_server.erl"},{line,32}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}} in context start_error
2018-10-30 11:01:15.210 [error] <0.536.0>CRASH REPORT Process <0.536.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,data_sup,{shutdown,{failed_to_start_child,data_server,{undef,[{mneisa,system_info,[extra_db_nodes],[]},{data_server,do_init,0,[{file,"/data/cellphone/_build/default/lib/cellphone/src/data/data_server.erl"},{line,63}]},{data_server,init,1,[{file,"/data/cellphone/_build/default/lib/cellphone/src/data/data_server.erl"},{line,32}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,...}]}}}}},...} in application_master:init/4 line 138
